### PR TITLE
Testing the stringlabels release

### PR DESCRIPTION
**Pull request by mcbenjemaa**
towards https://github.com/giantswarm/giantswarm/issues/26238

- Try prometheus with stringlabels
- Fix label version

### CODE REVIEW

**Comment by hervenicol** [comment]
I'd rather provide custom user-values than change the app's default value for this.

**Comment by QuantumEnigmaa** [comment]
On `goku` MC it's causing issue to the agent : 
```
Failed to pull image "docker.io/giantswarm/prometheus:v2.43.0-stringlabels"
```

**Comment by TheoBrigitte** [comment]
> > On `goku` MC it's causing issue to the agent :
> > ```
> > Failed to pull image "docker.io/giantswarm/prometheus:v2.43.0-stringlabels"
> > ```
> 
> I fixed that wink

How was this fixed ? This change should be in https://github.com/giantswarm/retagger

**Comment by mcbenjemaa** [comment]
Just used skopeo to sync the image manually,

**Comment by mcbenjemaa** [comment]
Deployed on gauss 

Screen Shot 2023-03-23 at 3 22 29 PM

**Comment by QuentinBisson** [comment]
What about logs? Cpu usage?

**Comment by mcbenjemaa** [comment]
CPU usage:

Screen Shot 2023-03-23 at 3 27 33 PM

**Comment by mcbenjemaa** [comment]
gauss 
Screen Shot 2023-03-23 at 3 28 30 PM

**Comment by QuentinBisson** [comment]
Can you let it run for 1-2 hours?

**Comment by mcbenjemaa** [comment]
goku

memory:

Screen Shot 2023-03-23 at 3 30 49 PM

CPU:
Screen Shot 2023-03-23 at 3 31 20 PM


Metrics are still sent to the Prometheus.

**Comment by TheoBrigitte** [comment]
We do have dashboards in Grafana to monitor Prometheus

**Comment by mcbenjemaa** [comment]
gauss: 

Screen Shot 2023-03-23 at 6 08 42 PM

CPU:

Screen Shot 2023-03-23 at 6 09 02 PM

**Comment by TheoBrigitte** [comment]
Looks like there are improvement on cpu and memory here. What do we do with this ? Maybe we don't change the default but we can use this on specific clusters to ease out situation when cpu/memory usage is high.

**Comment by hervenicol** [comment]
This means it will be used for the biggest clusters, meaning probably the most important clusters.

Do we prefer to have exceptions for the few biggest clusters, or use the same version of prometheus all around?

IMO, we could test it on some clusters for a short time (maybe a day?). 
If no critical issue shows up we can release a PMO that deploys this image.
It's easy to push, easy to revert as it's deployed via collections on the MCs.

**Comment by TheoBrigitte** [comment]
> IMO, we could test it on some clusters for a short time (maybe a day?). If no critical issue shows up we can release a PMO that deploys this image. It's easy to push, easy to revert as it's deployed via collections on the MCs.

I agree let's test this first.

**Pull request closed without merging**
