### PR TITLE
Add cluster singleton restriction, so installed only once

### PR DESCRIPTION
**Pull request by mcbenjemaa**
This PR:

- Add cluster singleton restriction, so installed only once

### Checklist

- [X] Update changelog in CHANGELOG.md.
- [ ] Test on Workload cluster.

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]

**Comment by mcbenjemaa** [comment]
Is namespace singleton better? 
Maybe customers wants to use this app! I wonder?

**Comment by QuentinBisson** [comment]
Why do we want singleton anyway? Sorry my mind was elsewhere

**Comment by QuentinBisson** [comment]
Why would customers not be able to deploy it in kube-system?

**Comment by QuentinBisson** [comment]
Let's close and keep this open to them

**Comment by mcbenjemaa** [comment]
Yeah, But was wondering about conflicts and Scraping conflicts

**Comment by QuentinBisson** [comment]
There are no conflicts. The choice we made to limit servicemonitor discovery to kube-system is temporary until we use a better alternative. That has no impact on customers

**Pull request merged**
